version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    container_name: ocean-api
    env_file: ./.env
    depends_on:
      - postgres
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    container_name: ocean-api-db
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - "$POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT"